-- Prints the live project's public schema as one block of SQL: the baseline migration
-- (plans/deployment.md, Phase 5 and D28). It only reads the catalogs and counts rows, so it
-- changes nothing. Run it in the Supabase SQL editor and copy the one cell it returns.
--
-- The block lists, in the order a new project needs them: extensions (as a comment), enum
-- types, sequences, tables, their keys and checks, foreign keys, other indexes, row level
-- security, policies, functions, triggers (including those on auth.users), and each table's
-- grants (as comments). It ends with a few counts about the books, as comments.
with
tables as (
  select c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity, c.relacl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')
),
columns as (
  select
    t.relname,
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || case
             when a.attidentity = 'a' then ' generated always as identity'
             when a.attidentity = 'd' then ' generated by default as identity'
             when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
             when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid)
             else ''
           end
        || case when a.attnotnull then ' not null' else '' end,
      E',\n' order by a.attnum
    ) as body
  from tables t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  group by t.relname
),
statements (section, name, stmt) as (
  select 0, '', '-- The public schema, printed ' || current_date || ' by scripts/sql/schemaSnapshot.sql.'
  union all
  select 1, '', '-- Extensions: ' || string_agg(extname || ' ' || extversion, ', ' order by extname)
  from pg_extension
  union all
  select 2, t.typname,
    'create type public.' || quote_ident(t.typname) || ' as enum ('
      || string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) || ');'
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace
  join pg_enum e on e.enumtypid = t.oid
  where n.nspname = 'public'
  group by t.typname
  union all
  -- Sequences behind serial columns; identity columns make their own.
  select 3, c.relname, 'create sequence if not exists public.' || quote_ident(c.relname) || ';'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'S'
    and not exists (select 1 from pg_depend dep where dep.objid = c.oid and dep.deptype = 'i')
  union all
  select 4, relname, 'create table public.' || quote_ident(relname) || E' (\n' || body || E'\n);'
  from columns
  union all
  select 5, t.relname || '.' || con.conname,
    'alter table public.' || quote_ident(t.relname) || ' add constraint ' || quote_ident(con.conname)
      || ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join tables t on t.oid = con.conrelid
  where con.contype in ('p', 'u', 'c', 'x')
  union all
  select 6, t.relname || '.' || con.conname,
    'alter table public.' || quote_ident(t.relname) || ' add constraint ' || quote_ident(con.conname)
      || ' ' || pg_get_constraintdef(con.oid) || ';'
  from pg_constraint con
  join tables t on t.oid = con.conrelid
  where con.contype = 'f'
  union all
  -- Indexes that no key or unique constraint already makes.
  select 7, t.relname || '.' || ic.relname, pg_get_indexdef(i.indexrelid) || ';'
  from pg_index i
  join tables t on t.oid = i.indrelid
  join pg_class ic on ic.oid = i.indexrelid
  where not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid)
  union all
  select 8, relname,
    'alter table public.' || quote_ident(relname) || ' enable row level security;'
      || case when relforcerowsecurity then E'\nalter table public.' || quote_ident(relname) || ' force row level security;' else '' end
  from tables
  where relrowsecurity
  union all
  select 9, tablename || '.' || policyname,
    'create policy ' || quote_ident(policyname) || ' on public.' || quote_ident(tablename)
      || ' as ' || lower(permissive) || ' for ' || lower(cmd)
      || ' to ' || array_to_string(roles, ', ')
      || coalesce(E'\n  using (' || qual || ')', '')
      || coalesce(E'\n  with check (' || with_check || ')', '') || ';'
  from pg_policies
  where schemaname = 'public'
  union all
  select 10, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    pg_get_functiondef(p.oid) || E';\n-- privileges: ' || coalesce(p.proacl::text, 'the defaults')
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend dep where dep.objid = p.oid and dep.deptype = 'e')
  union all
  -- Triggers on the public tables, and on auth.users (such as one that makes a profile row).
  select 11, c.relname || '.' || tg.tgname, pg_get_triggerdef(tg.oid) || ';'
  from pg_trigger tg
  join pg_class c on c.oid = tg.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  where not tg.tgisinternal
    and (n.nspname = 'public' or (n.nspname = 'auth' and c.relname = 'users'))
  union all
  select 12, relname, '-- grants on ' || relname || ': ' || coalesce(relacl::text, 'the defaults')
  from tables
  union all
  select 13, '1', '-- opening_books: ' || count(*) || ' rows, the longest name '
    || coalesce(max(char_length(name)), 0) || ' characters'
  from public.opening_books
  union all
  select 13, '2', '-- books by how many trees they hold: '
    || coalesce(string_agg(trees || ' ' || n, ', ' order by trees), 'none')
  from (select jsonb_array_length(trees) as trees, count(*) as n from public.opening_books group by 1) counts
  union all
  select 13, '3', '-- rows that point at books: drills ' || (select count(*) from public.drills)
    || ', training_sessions ' || (select count(*) from public.training_sessions)
    || ', user_position_stats ' || (select count(*) from public.user_position_stats)
)
select string_agg(stmt, E'\n\n' order by section, name) as snapshot
from statements;
